import '@app/styles/globals.scss'
import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'

import { mainMenu } from '@app/configs/main-menu.config'
import { montserratFont } from '@app/fonts'

import { Footer } from '@widgets/footer/footer'
import { Header } from '@widgets/header'

export const metadata: Metadata = {
  title: 'Nextjs project',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<React.PropsWithChildren & { modal: React.ReactNode }> = ({ children, modal }) => {
  return (
    <html lang="en">
      <body className={`${montserratFont.variable}`}>
        <NextTopLoader color="#000000" shadow={false} showSpinner={false} />

        <Header menuList={mainMenu} />

        <main>{children}</main>

        <Footer />

        {modal}
      </body>
    </html>
  )
}

export default RootLayout
